### ISSUE TITLE
Loading fixture files doesn't seem to work

### ISSUE THREAD

**Issue by huyh** [bradphelan/jasminerice#13]
I've tried to use loadFixtures function but it does not work. I inspected and find out the following code is used for loading fixture:

jasmine.Fixtures.prototype.createContainer_ = function(html) {
   var container = jQuery('<div id="' + this.containerId + '" />');
   container.html(html);
   jQuery('body').append(container);
}; 

but as far as I know we don't have the body tag at that time yet. So I thought it may be a bug

**Comment by dperrymorrow** [comment]
im having this issue as well, is there a quick fix for this that i can implement?

**Comment by netzpirat** [comment]
Jasminerice just provides a fixture controller and patches the fixture path in `jasmine-jquery`, so you can server your fixtures with Rails and thus use template languages like `haml`.

The Jasmine runner itself gets started when the window has loaded (see `jasminerice.js.coffee` where `window.onload` callback is assigned), so there should be body element.

But why do you guess that the `body` element may not available when you can set a breakpoint in your Web Developer Tool and **verify** your assumption.

**Comment by dpickett** [comment]
I had to remove my jquery.js and jquery-jasmine.js helper files and I was able to get fixtures working

**Comment by phuongnd08** [comment]
@dpickett: jasminerice use a (mod-ed) version of jquery-jasmine already.

**Comment by olivierntk** [comment]
Hi all, 

I am having as well issues loading fixtures. Using rails 3.2.2 and the latest of the jasminerice gem.

My fixture is: /spec/javascripts/fixtures/device_edit.html.

When starting the app, navigating to: http://localhost:3000/jasmine/fixtures/device_edit renders the template fine.

However, the jasmine runner is unable to load the fixture because it is trying to load the fixture at:

http://localhost:3000/spec/javascripts/fixtures/device_edit

Here is how I call the fixture in my spec: loadFixtures 'device_edit'

I can see in the jasminerice code:

In spec_controller.rb 

def fixtures
      render "spec/javascripts/fixtures/#{params[:filename]}"
end

Has anybody encountered this issue?

**Comment by phuongnd08** [comment]
@olivierntk: Are you loading fixtures with something like `loadFixtures("/spec/javascripts/fixtures/device_edit")`? You should omit the path, `loadFixtures("device_edit")` is enough

**Comment by olivierntk** [comment]
@phuongnd08 Yes I do ... I put a sample project at: https://github.com/olivierntk/jasmine_test if somebody could take a look and let me know where my silly mistake is, that'd be great! Thx!

**Comment by phuongnd08** [comment]
You put your jasmine-jquery.js inside spec/javascript. I already mentioned above that jasminerice already provide its own modded version of jasmine-jquery.js and thus you don't have to and should not do. Remove that file should solve your problem.

**Comment by olivierntk** [comment]
Thank you, that solved it!
