### ISSUE TITLE
Problem referencing code under test and utility code.

### ISSUE THREAD

**Issue by colin-jack** [bradphelan/jasminerice#28]
I have this structure:

.
├── app
│   ├── assets
│   │   ├── javascripts
│   │   │   └── wizard
│   │   │       ├── wizard.js.coffee
├── spec
│   ├── javascripts
│   │   └── wizard
│   │       └── wizard_object_mother_spec.js.coffee
│   │       └── wizard_spec.js.coffee

Then in the wizard_spec.js.coffee I have:

``` coffeescript
#= require wizard/wizard
#= require ./wizard_object_mother_spec

describe "Wizard", ->
  describe "When a wizard has only one step", ->
    beforeEach ->
      #@wizardName = "Wizard Name"
      #@firstStep = new AlwaysCompleteAndValidStep()

      @wizard = new Wizard(@wizardName, null)
      ...
```

The problem is the specs in wizard_spec.js.coffee can't see the classes in "wizard.js.coffee" and "wizard_object_mother_spec.js.coffee". I can see that Jasmine is loading in the files but they're not being brought into the Javascript file containing the tests. I'm thus wondering whether I'm doing something wrong or if this is not supported?

**Comment by tonchis** [comment]
Hey there! I'm sorry to bother, I'm having the same problem but I can't seem to solve it. My directory structure is pretty similar (using Rails 3.1.3):
- app/assets/javascripts/dilemmas/dilemmas.js.coffee
- app/assets/javascripts/dilemmas/dilemma.js.coffee
  and specs:
- spec/javascripts/spec.coffee
- spec/javascripts/dilemmas_spec.coffee

I'm able to require "dilemmas/dilemmas" and "dilemmas/dilemma" in my spec.coffee file, and I get no error from Sprockets whatsoever (actually I see the file loaded in the head of /jasmine page). However in my dilemmas_spec.coffee file, when I call the variable Dilemma, I get "ReferenceError: Dilemma is not defined" (same with Dilemmas).

I see the issue is closed, but no conclusion on how to deal with this :(
Thanks again and sorry for the inconvenience.

**Comment by techpeace** [comment]
You'll probably find the answer [here](http://stackoverflow.com/questions/8580473/getting-jasmine-specs-written-in-coffeescript-to-run).
