### ISSUE TITLE
Add support for test-unit/minitest

### ISSUE THREAD

**Issue by jmacdonald** [bradphelan/jasminerice#30]
I realize that Jasmine is a BDD test framework, but for those of us who haven't jumped on the rspec bandwagon, having coffee/javascript testing alongside our other tests would be wonderful.

**Comment by metaskills** [comment]
Just passing by and thought I would comment. 

I am having a hard time following what this request means. Let me see if I can explain a few things from my perspective to see if this can spawn some good feedback for the author here.

First, I'm not sure many people get BDD/TDD right. Heck I may have it wrong at times. Myself, I just TATFTDD... I digress. Things like Test::Unit, MiniTest, RSpec are all just tools and you can unit, functional, integration, and behavior test with. Just because a testing framework has describe/it or context/should methods does not mean it is a "x"DD test framework. Case in point, MiniTest::Unit is the super class for MiniTest::Spec (basically a syntactic sugar on top of it) and I use this as my base testing for everything from Rails to various gem. Some of my articles are mentioned in this post. http://www.rubyinside.com/a-minitestspec-tutorial-elegant-spec-style-testing-that-comes-with-ruby-5354.html

So back to Jasmine, from my current experience with it. It leans more to a unit testing framework for JavaScript. Perhaps more useful in TDD too. Things like Capybara and my personal favorite Capybara-WebKit are integration/behavior test tools, and I drive those tests from MiniTest too.

So what would this issue be asking for? Perhaps you just want to run `$ rake test` in your rails app and have it run the jasmine tests after the default test:units, test:functionals, and test:integration tasks?

**Comment by jmacdonald** [comment]
Apologies for the semantic confusion; I shouldn't have mentioned RSpec right after referencing BDD, because RSpec isn't a behaviour driven test framework. Cucumber would be more akin to this (which runs on RSpec), and the syntax is quite different from other testing libraries. There is definitely a difference between TDD and BDD, but my comment didn't properly explain what I was asking for. Also, to add to the confusion, Jasmine does label itself as a BDD framework, even though I completely agree that tests written for it look identical to standard unit tests.

The jasminerice gem puts files into spec/ and depends on spec/spec_helper.rb, and I'm pretty sure it lists RSpec as a dependency. I'd like to have this gem work with the out-of-the-box TestUnit setup, and exactly as you mentioned, have it integrate with rake alongside unit, functional, and integration tests.

Hope that helps!

**Comment by bradphelan** [comment]
The library has no dependency on rspec or any other ruby bdd/tdd/sdd/fdd library. It's pure javascript utilizing the asset pipeline to pull it together. It's just a lightweight wrapper for making it easy to use the jasmine js libraries. Any feature requests on the notation for that library should be directed to it's authors.
