### ISSUE TITLE
Release new gem version

### ISSUE THREAD

**Issue by prashantrajan** [bradphelan/jasminerice#86]
Perhaps it's time for a new release? 0.0.10 was released on October 15, 2012.

There's stuff in the README that is not present in the existing gem version, e.g. loading json fixtures.

**Comment by jrreed** [comment]
+1 

I personally just need the support for jasmine 1.3.1, which includes a fix that suppresses pretty-printing of inherited attributes on objects. When it tries to output a backbone(-relational) object it doesn't hang and fail trying to print the entire object graph.

https://github.com/pivotal/jasmine/pull/290

**Comment by gmcnaughton** [comment]
+1

Would like to see jasmine 1.3.1 get pulled in to the released gem!

**Comment by jejacks0n** [comment]
I'm helping Brad on the project for a bit, and this is one of the things I hope to address.

**Comment by hmayer00** [comment]
Thanks for picking this up jejacks0n.  I see you bumped the version in master just a few hours ago.  Can't wait for jasmine not to crash on the backbone objects!

**Comment by jejacks0n** [comment]
An update:

I've contacted Brad about releasing the gem and adding the project to [Travis CI](https://travis-ci.org/), but haven't heard back in a few days.  I know he's no longer able to maintain the project, so I'm working at either having a consistent way to release the gem, or having him shift ownership elsewhere.

I've written my own Javascript runner for Rails called [Teabag](https://github.com/modeset/teabag) which is as simple as Jasminerice to setup, but is more feature rich (command line interface, running headlessly, custom reporters, etc.)

While I'll continue contributing to Jasminerice because I like the project and think it's good, I would also encourage checking out Teabag as a potential alternative.  I've provided some information that might help.

Background: https://github.com/modeset/teabag/wiki/The-Story-%28as-told-by-jejacks0n%29
Migrating: https://github.com/modeset/teabag/wiki/Migrating-from-Jasminerice

**Comment by conzett** [comment]
Any update on this? Teabag looks cool and I'll be sure to check it out for future projects, but I have a few projects with tests built on Jasmine with jasminerice at the moment and it would be great to have a new gem release cut. If that's not doable would it be possible to at least tag some more recent stable releases on GitHub to use with Bundler?

**Comment by lenntt** [comment]
would like an update to.
for now, I've released the gem on my own (private) gemserver. FYI here's how:
checkout the project and `gem build jasminerice.gemspec`

**Comment by bruno-** [comment]
Hey guys, just another +1 for releasing new gem version. I've spent an hour today trying to get [multiple-suites](https://github.com/bradphelan/jasminerice/wiki/Multiple-Suites) working after figuring out I have old gem version.

**Comment by DavidAllison** [comment]
@jejacks0n Any reason why someone wouldn't switch to Teabag from jasminerice? I'm also in need of an updated release but I saw your comment above. Is there anything that Teabag is missing/doesn't do that jasminerice did/does?

**Comment by jejacks0n** [comment]
Not that I'm aware of, but simplicity is meaningful if it suits your needs, and that's where I think Jasminerice is useful and why I contribute to it.  Teabag is as simple from an initial setup perspective, but it's not as simple as Jasminerice -- inherently you trade some complexity for a larger feature set with something like a testing framework.

Personally I would encourage anyone to migrate, but those choices should be influenced by your specific case.  If you're starting a new project, absolutely.  If you're migrating an existing well matured project, meh, look at the big picture of what time you'd spend and what you'd gain/use. =)

**Comment by nathany** [comment]
@jejacks0n I hope @bradphelan gets you the necessary RubyGems permissions to push a new release.

We may look into migrating to Teabag. Thanks for writing up a migration guide.

**Comment by lukeasrodgers** [comment]
Just wondering if a version bump for this gem might still be possible. I'm using Teaspoon in another project and it's great, and I can point at commits in this repo in my Gemfile to use the latest for projects still using jasminerice, but that isn't quite ideal.
