### ISSUE TITLE
Make gem compatible to Rails Edge

### ISSUE THREAD

**Issue by leifg** [bradphelan/jasminerice#88]
I am currently on a little project using Rails 4.0.0 ([bf095770e561c51cebeb5a556afc03a21d9e603c](https://github.com/rails/rails/tree/bf095770e561c51cebeb5a556afc03a21d9e603c) to be specific).

I wanted to use jasminerice but it turned out that this gem is somehow not compatible.

Even after fixing the errors, that prevent the server to start (see [my fork](https://github.com/leifg/jasminerice) for details, the running of the specs doesn't work (going to /jasmine just puts out a blank page).

It looks like the path to the whole asset pipeline is wrong:

```
...
<link href="/jasmine/assets/jasmine.css?body=1" media="screen" rel="stylesheet" />
<link href="/jasmine/assets/application.css?body=1" media="screen" rel="stylesheet" />
<link href="/jasmine/assets/spec.css?body=1" media="screen" rel="stylesheet" />
<script src="/jasmine/assets/jasmine.js?body=1"></script>
<script src="/jasmine/assets/jasmine-html.js?body=1"></script>
<script src="/jasmine/assets/jasmine-jquery-1.4.2.js?body=1"></script>
<script src="/jasmine/assets/jasminerice.js?body=1"></script>
<script src="/jasmine/assets/jquery.js?body=1"></script>
<script src="/jasmine/assets/jquery_ujs.js?body=1"></script>
<script src="/jasmine/assets/hello.js?body=1"></script>
<script src="/jasmine/assets/application.js?body=1"></script>
<script src="/jasmine/assets/sanity_spec.js?body=1"></script>
<script src="/jasmine/assets/sanityjs_spec.js?body=1"></script>
<script src="/jasmine/assets/spec.js?body=1"></script>
```

   ...

It all starts with /jasmine.

See my [example project](https://github.com/leifg/jasmine-rails40-example) for details

**Comment by kstevens715** [comment]
@leifg, I was having the same problem and independently forked and fixed in almost the same way you did. Yours actually fixed one problem mine didn't. But anyway, for me this was all that was needed to get it working with Rails edge. If you're still having trouble, feel free to check out my working app: https://github.com/kstevens715/rumoney/tree/1f00a6f0894737b7389

Are you planning on issuing a pull request for this?

**Comment by jejacks0n** [comment]
@kstevens, I'm currently contributing to the project and bringing Jasminerice up to date -- and addressing several of the issues.

If you would like to issue a pull request I'd like to get a gauge on what it is that needs attention and get it merged in.  I'm currently working on getting specs into the project so I can feel more comfortable making some of these changes (as I know there's several things built on top of Jasminerice).

Full disclosure: I wrote a project called [Teabag](https://github.com/modeset/teabag) that is compatible with Rails 4, but I want the community to retain a more simplistic solution like Jasminerice.

**Comment by kstevens715** [comment]
@jejacks0n, that's funny I was just getting ready to email you, because of all the changes you've been working on. I wonder if @bradphelan would be interested in turning over maintenance of the project to you (just because he said it's looking for a new home). This is a great project, so I'd love to see it kept up. Although it's the first I heard of it, Teabag looks very nice too.

I can certainly do a pull request, although @leifg deserves the credit. I can have something ready in a few...

**Comment by jejacks0n** [comment]
I saw that notice a few days ago, and offered, so he gave me collaboration.  I do have the ability to merge pull requests, but I'm giving it time and will make sure all of my changes don't break the tests I'm working on at the moment.

I'll update the readme shortly explaining the situation, but it will remain under @bradphelan.  He's been super good about merging pull requests, so I expect with a little community effort we can get most of the issues resolved / closed as well as making it easier for others to contribute.

**Comment by kstevens715** [comment]
Great, very happy to hear that. I just sent a pull request for Rails 4 routing.
